# This script is part of the captureKNX project, which logs all KNX bus traffic to an InfluxDb for reporting via Grafana
# https://github.com/greiginsydney/captureKNX
# https://greiginsydney.com/captureKNX


apiVersion: 1

datasources:
  - name: captureKNX
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      dbName: captureKNX
      httpMode: POST
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token changeme'
      

# Reference:
# https://grafana.com/docs/grafana/latest/datasources/influxdb/#provision-the-data-source
